### ISSUE TITLE
invalid conversion from ‘void (*)(uvc_frame*)’ to ‘void (*)(uvc_frame*, void*)’ [-fpermissive]

### ISSUE THREAD

**Issue by btbouwens** [CyberCastle/jLibuvc#1]
I tried to build jLibuvc, but encountered:

```
/home/bram/project/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp: In function ‘jint Java_cl_cc_jlibuvc_UVCController_uvc_1start_1streaming(JNIEnv*, jclass, jobject, jobject, jobject, jobject, jbyte)’:
/home/bram/project/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp:3541:99: error: invalid conversion from ‘void (*)(uvc_frame*)’ to ‘void (*)(uvc_frame*, void*)’ [-fpermissive]
         int rvalue = uvc_start_streaming(ptr0, ptr1, (ptr2 == NULL ? NULL : ptr2->ptr), ptr3, arg4);
                                                                                                   ^
In file included from /home/bram/project/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp:62:0:
/usr/local/include/libuvc/libuvc.h:512:13: error:   initializing argument 3 of ‘uvc_error_t uvc_start_streaming(uvc_device_handle_t*, uvc_stream_ctrl_t*, void (*)(uvc_frame*, void*), void*, uint8_t)’ [-fpermissive]
 uvc_error_t uvc_start_streaming(
             ^
Generating /home/bram/project/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp
Compiling /home/bram/project/jLibuvc/target/classes/cl/cc/jlibuvc/linux-x86_64/libjniUVCController.so
g++ -I/usr/local/jdk1.7.0_60/include -I/usr/local/jdk1.7.0_60/include/linux /home/bram/project/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp -luvc -Wl,-rpath,$ORIGIN/ -march=x86-64 -m64 -Wall -O3 -fPIC -shared -s -o /home/bram/project/jLibuvc/target/classes/cl/cc/jlibuvc/linux-x86_64/libjniUVCController.so 
```

to me this looks like UVCFrameCallback does not match

```
typedef void(uvc_frame_callback_t)(struct uvc_frame *frame, void *user_ptr);
```

but I'm not familiar with these structures.

**Comment by CyberCastle** [comment]
Hi,

What operating system, compiled tool and libuvc version are you using ?

Greetings

**Comment by btbouwens** [comment]
Hi!

I’m using Fedora 19, with Java 1.7.0_60, and the usual tools, like gcc 4.8.3.

I played around a bit more, with a 640x480 camera, and it worked with

diff --git a/src/main/java/cl/cc/example/Run.java b/src/main/java/cl/cc/example/Run.java
index 81bdb40..7a7a244 100644
--- a/src/main/java/cl/cc/example/Run.java
+++ b/src/main/java/cl/cc/example/Run.java
@@ -11,6 +11,7 @@ import cl.cc.jlibuvc.UVCController.UVCFrameCallback;
 import cl.cc.jlibuvc.UVCController.UVCFrameFormat;
 import cl.cc.jlibuvc.UVCController.UVCStreamCtrl;
 import cl.cc.jlibuvc.Utils;
+import org.bytedeco.javacpp.Pointer;
 import org.bytedeco.javacpp.PointerPointer;

 /**
@@ -37,7 +38,7 @@ public class Run {
         UVCDeviceDescriptor desc = descp.get(UVCController.UVCDeviceDescriptor.class);
         System.out.println("Serial Number: " + desc.serialNumber().getString());
         System.out.println("Manufacturer: " + desc.manufacturer());
-        System.out.println("Product Description: " + desc.product().getString());
- ```
     System.out.println("Product Description: " + desc.product());
   UVCController.uvc_free_device_descriptor(desc);
  
   // Obtención de la descripción del formato
  ```
  
  @@ -51,7 +52,7 @@ public class Run {
       System.out.println("Frame Descriptors: " + frmtDesc.bNumFrameDescriptors());
       System.out.println("Interlace Flags: " + frmtDesc.bmInterlaceFlags());
- ```
     int res = UVCController.uvc_get_stream_ctrl_format_size(devh, sctrl, UVCFrameFormat.UVC_FRAME_FORMAT_MJPEG, 1280, 720, 30);
  ```
- ```
     int res = UVCController.uvc_get_stream_ctrl_format_size(devh, sctrl, UVCFrameFormat.UVC_FRAME_FORMAT_MJPEG, 640, 480, 15);
   System.out.println("Get Stream Control Result: " + res);
  
   if (res != 0) {
  ```
  
  @@ -65,11 +66,11 @@ public class Run {
       System.out.println("Interface Number: " + sctrl.bInterfaceNumber());
  
  ```
   final DemoFrame windows = new DemoFrame("Sonria!!!!!! :-)");
  ```
-        windows.setSize(1280, 720);
- ```
     windows.setSize(640, 480);
   UVCFrameCallback callback = new UVCFrameCallback() {
  
       @Override
  ```
-            public void call(UVCFrame frame) {
- ```
         public void call(UVCFrame frame, Pointer userPointer) {
  
           try {
               UVCFrame cframe = UVCController.uvc_allocate_frame(frame.width() * frame.height());
  ```
  
  diff --git a/src/main/java/cl/cc/jlibuvc/UVCController.java b/src/main/java/cl/cc/jlibuvc/UVCController.java
  index 3747827..3f27774 100644
  --- a/src/main/java/cl/cc/jlibuvc/UVCController.java
  +++ b/src/main/java/cl/cc/jlibuvc/UVCController.java
  @@ -539,11 +539,11 @@ public class UVCController implements InfoMapper {
  
  ```
   private native void allocate();
  ```
- ```
     protected void call(UVCFrame frame, Pointer user_ptr){
  ```
-            this.call(frame);
-        }
-        //protected void call(UVCFrame frame, Pointer user_ptr){
-            //this.call(frame);
- ```
     //}
  ```
- ```
     public abstract void call(UVCFrame frame);
  ```
- ```
     public abstract void call(UVCFrame frame, Pointer user_ptr);
  ```
  
   }
  
   /\* Métodos para detectar y abrir un dispositivo UVC */

For me desc.product() and desc.manufacturer() were null.

Regards,

Bram

On 24 Oct 2014, at 16:49, CyberCastle notifications@github.com wrote:

> Hi,
> What operating system and compiled tool are you using?
> 
> Greetings
> 
> —
> Reply to this email directly or view it on GitHub.

**Comment by CyberCastle** [comment]
Hi,

I can't reproduce the error which you refer. ¿What version off LibUVC are you using?

Greetings

**Comment by btbouwens** [comment]
It's the current version from https://github.com/ktossell/libuvc .
Last changed Aug 12.
I'll try to reproduce on a debian box this week.

**Comment by btbouwens** [comment]
On an Ubuntu box:

```
[INFO] --- exec-maven-plugin:1.3.1:exec (build-jnilib) @ jLibUVC ---
/home/bram/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp: In function ‘jint Java_cl_cc_jlibuvc_UVCController_uvc_1start_1streaming(JNIEnv*, jclass, jobject, jobject, jobject, jobject, jbyte)’:
/home/bram/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp:3541:99: error: invalid conversion from ‘void (*)(uvc_frame*)’ to ‘void (*)(uvc_frame*, void*)’ [-fpermissive]
/usr/local/include/libuvc/libuvc.h:512:13: error:   initializing argument 3 of ‘uvc_error_t uvc_start_streaming(uvc_device_handle_t*, uvc_stream_ctrl_t*, void (*)(uvc_frame*, void*), void*, uint8_t)’ [-fpermissive]
Generating /home/bram/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp
Compiling /home/bram/jLibuvc/target/classes/cl/cc/jlibuvc/linux-x86_64/libjniUVCController.so
g++ -I/usr/lib/jvm/java-7-oracle/include -I/usr/lib/jvm/java-7-oracle/include/linux /home/bram/jLibuvc/target/classes/cl/cc/jlibuvc/jniUVCController.cpp -luvc -Wl,-rpath,$ORIGIN/ -march=x86-64 -m64 -Wall -O3 -fPIC -shared -s -o /home/bram/jLibuvc/target/classes/cl/cc/jlibuvc/linux-x86_64/libjniUVCController.so
```

with libusb-1.0-0-dev and the latest libuvc on 3.13.0-37-generic #64~precise1-Ubuntu

**Comment by CyberCastle** [comment]
Hi
For now, I don´t have answer for this issue.... I'm developing in a Mac, and I can't reproduce it. 
In the week I'll make a linux environment to check this issue.

Greetings

**Comment by CyberCastle** [comment]
Hi:
Test new version, please.

Greetings
