### ISSUE TITLE
uvc_get_pantilt_abs format

### ISSUE THREAD

**Issue by nospam2k** [CyberCastle/jLibuvc#10]
```
...
IntPointer curPan = new IntPointer();
IntPointer curTilt = new IntPointer();
UVCController.uvc_get_pantilt_abs(devh, curPan, curTilt, UVCController.UVCReqCode.UVC_GET_INFO);
System.out.println(curPan.get(0));
```

curPan.get(0) always returns null pointer.
UVC_GET_CUR crashes

**Comment by CyberCastle** [comment]
Can you tell me what is the model of the camera with which you are testing this library, please?

**Comment by nospam2k** [comment]
Aver CAM520

**Comment by nospam2k** [comment]
So maybe a better question is when I send a request for absolute pan, for example, how can I watch for when the move is complete?

My goal is to turn on autofocus, pan, and then turn off auto focus. If I just send these commands, since they are asynchronous, the auto focus is turned off before the camera completes movement.

**Comment by CyberCastle** [comment]
I do not know how to control PTZ cameras via UVC protocol or another. Sorry, I don't know how to help you. I suggest the following:

- Check if the PTZ parameters of the camera can be controlled via UVC.
- Ask this question directly to the [team behind libuvc](https://github.com/libuvc/libuvc).

**Comment by nospam2k** [comment]
Ok, thx.

**Comment by CyberCastle** [comment]
Closing this thread.
