### ISSUE TITLE
uvc_get_device_list

### ISSUE THREAD

**Issue by lobsteroh** [CyberCastle/jLibuvc#3]
hi, i am eager to use the following C call

`uvc_error_t uvc_get_device_list (uvc_context_t * ctx, uvc_device_t *** list)`

 via javacpp and I am struggling with the part that returns the list. my initial stab at this one is ...

`public static native int uvc_get_device_list(UVCContext ctx, @Cast("uvc_device_t***") list);`

but that really was just a first guess. any suggestions on how to make this call work? thanks

**Comment by CyberCastle** [comment]
Hi

I didn't use that function, sorry. If you view my example, I used UVCController.uvc_find_device function for automatic detection....

Greetings

**Comment by lobsteroh** [comment]
hi, thanks. yes, i saw that one and it works well but i have several identical cameras plugged in to track from multiple angles at the same time and i need to figure out a way to set the parameters for each one unambiguously. i can step through the usb device list with libusb and get the tree with a recursive search of the bus. i am trying to figure out a way to do that for the uvc devices of that tree as well. the getdevicelist call looks like a solution. i will check with the javacpp list for advice. thanks again

**Comment by lobsteroh** [comment]
I have forked jLibuvc and with the help of folks at javacpp i have added a functional wrapper for uvc_get_device_list as...

public static native int uvc_get_device_list(UVCContext ctx, @Cast("uvc_device***") @ByPtrPtr PointerPointer<?> uvcDevList);

i then access a device from the list with the following code ...

```
public class Load { 
    public static void main(String... arg) throws InterruptedException {
        UVCDevice dev = new UVCController.UVCDevice();
        UVCContext ctx = new UVCController.UVCContext();
        UVCStreamCtrl sctrl = new UVCController.UVCStreamCtrl();
        System.out.println("Initialize : " + UVCController.uvc_init(ctx, null));

//      this accesses the default cam ...
//      System.out.println("Find Camera: " + UVCController.uvc_find_device(ctx, dev, 0x0, 0x0, null));

//      this is how to get the list and pull the default device from it
        PointerPointer<UVCDevice> uvcDevList = new PointerPointer<UVCDevice>();
        UVCController.uvc_get_device_list(ctx, uvcDevList);        
        dev = (UVCDevice) uvcDevList.get(UVCDevice.class, 0);

//      freeing the device list does not work yet...
//      UVCController.uvc_free_device_list(uvcDevList,1);

        UVCController.uvc_unref_device(dev);
        UVCController.uvc_exit(ctx);
    }
}
```

works like a charm up to here, but freeing the list at the end still needs to be implemented.
