### ISSUE TITLE
usbContext

### ISSUE THREAD

**Issue by lobsteroh** [CyberCastle/jLibuvc#8]
i can get a usb handle for a device handle in libuvc with

```
libusb_device_handle* uvc_get_libusb_handle (uvc_device_handle_t* devh) 
```

but I don't know how to handle the return part in jLibuvc ... any recommendations for how to get the usb device info? thanks,

**Comment by CyberCastle** [comment]
Hi
Sorry, but I also don't know get the usb device info........ "libusb_device_handle" is a object from libusb.
Please, check https://github.com/usb4java/libusb4java for more info.

Greetings
